// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: measurement.proto
#ifndef GRPC_measurement_2eproto__INCLUDED
#define GRPC_measurement_2eproto__INCLUDED

#include "measurement.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class MeasurementService final {
 public:
  static constexpr char const* service_full_name() {
    return "MeasurementService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status NewMeasurement(::grpc::ClientContext* context, const ::Measurement& request, ::OK* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::OK>> AsyncNewMeasurement(::grpc::ClientContext* context, const ::Measurement& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::OK>>(AsyncNewMeasurementRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::OK>> PrepareAsyncNewMeasurement(::grpc::ClientContext* context, const ::Measurement& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::OK>>(PrepareAsyncNewMeasurementRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void NewMeasurement(::grpc::ClientContext* context, const ::Measurement* request, ::OK* response, std::function<void(::grpc::Status)>) = 0;
      virtual void NewMeasurement(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::OK* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void NewMeasurement(::grpc::ClientContext* context, const ::Measurement* request, ::OK* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void NewMeasurement(::grpc::ClientContext* context, const ::Measurement* request, ::OK* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void NewMeasurement(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::OK* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void NewMeasurement(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::OK* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::OK>* AsyncNewMeasurementRaw(::grpc::ClientContext* context, const ::Measurement& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::OK>* PrepareAsyncNewMeasurementRaw(::grpc::ClientContext* context, const ::Measurement& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status NewMeasurement(::grpc::ClientContext* context, const ::Measurement& request, ::OK* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::OK>> AsyncNewMeasurement(::grpc::ClientContext* context, const ::Measurement& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::OK>>(AsyncNewMeasurementRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::OK>> PrepareAsyncNewMeasurement(::grpc::ClientContext* context, const ::Measurement& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::OK>>(PrepareAsyncNewMeasurementRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void NewMeasurement(::grpc::ClientContext* context, const ::Measurement* request, ::OK* response, std::function<void(::grpc::Status)>) override;
      void NewMeasurement(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::OK* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void NewMeasurement(::grpc::ClientContext* context, const ::Measurement* request, ::OK* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void NewMeasurement(::grpc::ClientContext* context, const ::Measurement* request, ::OK* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void NewMeasurement(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::OK* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void NewMeasurement(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::OK* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::OK>* AsyncNewMeasurementRaw(::grpc::ClientContext* context, const ::Measurement& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::OK>* PrepareAsyncNewMeasurementRaw(::grpc::ClientContext* context, const ::Measurement& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_NewMeasurement_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status NewMeasurement(::grpc::ServerContext* context, const ::Measurement* request, ::OK* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_NewMeasurement : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_NewMeasurement() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_NewMeasurement() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewMeasurement(::grpc::ServerContext* /*context*/, const ::Measurement* /*request*/, ::OK* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNewMeasurement(::grpc::ServerContext* context, ::Measurement* request, ::grpc::ServerAsyncResponseWriter< ::OK>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_NewMeasurement<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_NewMeasurement : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_NewMeasurement() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::Measurement, ::OK>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::Measurement* request, ::OK* response) { return this->NewMeasurement(context, request, response); }));}
    void SetMessageAllocatorFor_NewMeasurement(
        ::grpc::experimental::MessageAllocator< ::Measurement, ::OK>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::Measurement, ::OK>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_NewMeasurement() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewMeasurement(::grpc::ServerContext* /*context*/, const ::Measurement* /*request*/, ::OK* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* NewMeasurement(
      ::grpc::CallbackServerContext* /*context*/, const ::Measurement* /*request*/, ::OK* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* NewMeasurement(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::Measurement* /*request*/, ::OK* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_NewMeasurement<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_NewMeasurement<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_NewMeasurement : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_NewMeasurement() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_NewMeasurement() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewMeasurement(::grpc::ServerContext* /*context*/, const ::Measurement* /*request*/, ::OK* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_NewMeasurement : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_NewMeasurement() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_NewMeasurement() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewMeasurement(::grpc::ServerContext* /*context*/, const ::Measurement* /*request*/, ::OK* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNewMeasurement(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_NewMeasurement : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_NewMeasurement() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->NewMeasurement(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_NewMeasurement() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewMeasurement(::grpc::ServerContext* /*context*/, const ::Measurement* /*request*/, ::OK* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* NewMeasurement(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* NewMeasurement(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_NewMeasurement : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_NewMeasurement() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::Measurement, ::OK>(std::bind(&WithStreamedUnaryMethod_NewMeasurement<BaseClass>::StreamedNewMeasurement, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_NewMeasurement() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status NewMeasurement(::grpc::ServerContext* /*context*/, const ::Measurement* /*request*/, ::OK* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedNewMeasurement(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Measurement,::OK>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_NewMeasurement<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_NewMeasurement<Service > StreamedService;
};


#endif  // GRPC_measurement_2eproto__INCLUDED
