// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: measurement.proto

#include "measurement.pb.h"
#include "measurement.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* MeasurementService_method_names[] = {
  "/MeasurementService/NewMeasurement",
};

std::unique_ptr< MeasurementService::Stub> MeasurementService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MeasurementService::Stub> stub(new MeasurementService::Stub(channel));
  return stub;
}

MeasurementService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_NewMeasurement_(MeasurementService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MeasurementService::Stub::NewMeasurement(::grpc::ClientContext* context, const ::Measurement& request, ::OK* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_NewMeasurement_, context, request, response);
}

void MeasurementService::Stub::experimental_async::NewMeasurement(::grpc::ClientContext* context, const ::Measurement* request, ::OK* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_NewMeasurement_, context, request, response, std::move(f));
}

void MeasurementService::Stub::experimental_async::NewMeasurement(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::OK* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_NewMeasurement_, context, request, response, std::move(f));
}

void MeasurementService::Stub::experimental_async::NewMeasurement(::grpc::ClientContext* context, const ::Measurement* request, ::OK* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_NewMeasurement_, context, request, response, reactor);
}

void MeasurementService::Stub::experimental_async::NewMeasurement(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::OK* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_NewMeasurement_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::OK>* MeasurementService::Stub::AsyncNewMeasurementRaw(::grpc::ClientContext* context, const ::Measurement& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::OK>::Create(channel_.get(), cq, rpcmethod_NewMeasurement_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OK>* MeasurementService::Stub::PrepareAsyncNewMeasurementRaw(::grpc::ClientContext* context, const ::Measurement& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::OK>::Create(channel_.get(), cq, rpcmethod_NewMeasurement_, context, request, false);
}

MeasurementService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MeasurementService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MeasurementService::Service, ::Measurement, ::OK>(
          std::mem_fn(&MeasurementService::Service::NewMeasurement), this)));
}

MeasurementService::Service::~Service() {
}

::grpc::Status MeasurementService::Service::NewMeasurement(::grpc::ServerContext* context, const ::Measurement* request, ::OK* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


